version: '3.8'

services:
  # Base de Datos
  michicode-mongo:
    image: mongo:6
    container_name: michicode-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - michicode-net

  # Backend
  backend:
    image: ${DOCKER_USER}/michicode-backend:latest
    container_name: backend
    restart: always
    environment:
      PORT: 5000
      MONGODB_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@michicode-mongo:27017/michicode?authSource=admin"
      BASE_URL: http://${EC2_HOST_DNS}:5000
    ports:
      - "5000:5000"
    depends_on:
      - michicode-mongo
    networks:
      - michicode-net

  # Frontend
  frontend:
    image: ${DOCKER_USER}/michicode-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - michicode-net

  # Monitoreo
  prometheus:
    image: prom/prometheus:latest
    container_name: michicode-prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - michicode-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: michicode-grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - michicode-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: michicode-node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - michicode-net

  loki:
    image: grafana/loki:2.9.0
    container_name: michicode-loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - michicode-net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: michicode-promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - michicode-net

networks:
  michicode-net:
    driver: bridge

volumes:
  mongo-data:
  grafana-storage: