version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: michicode-mongo
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: michicode
    volumes:
      - mongo-data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: michicode-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://root:rootpassword@mongo:27017/michicode?authSource=admin
      BASE_URL: http://localhost:5000
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:5000 
    container_name: michicode-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: